# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Ahorros'), (2, 'Corriente'), (3, 'Otra')], default=1),
        ),
    ]
