# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_transaccion_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetadebito',
            name='numero',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
